apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-development-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anupamduttadevops/kubernetes.git
    targetRevision: development
    path: environments/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
