apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
     - objectName: "CSIsecret" 
       objectType: "secretsmanager"
  secretObjects:                           # New field for syncing secrets
    - secretName: database-credentials     # Name of the Kubernetes Secret
      type: Opaque
      data:
        - objectName: "CSIdriver"          # The same objectName as above
          key: "db-credentials" 