apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      serviceAccountName: production
      volumes:
        - name: csi-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretsProviderClass: database-aws-secrets
      containers:
        - name: app-container
          image: anupamdevops/environments:development
          ports:
            - containerPort: 80
          volumeMounts:
            - name: csi-volume
              mountPath: /mnt/secrets-store
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "512Mi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "256Mi"
