apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: production
      initContainers:
      - name: init-secrets
        image: busybox
        command: ['sh', '-c', 'cat /mnt/secrets-store/CSIsecret | sed -e "s/[{}]//g" -e "s/\"//g" -e "s/:/=/g" -e "s/,/\\n/g" > /mnt/secrets-store/secrets.env']
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: secrets-env
          mountPath: "/mnt/secrets-store"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: secrets-env-config
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: secrets-env
          mountPath: "/mnt/secrets-store"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "database-aws-secrets"
      - name: secrets-env
        emptyDir: {}
